function[ Constant, concentration]=fun_concentration_bin(...
    ...
 xx               , AAA       , upper_bound_save , Trace_size    , ...
 concen_radious   , PSF_Func  , b                , concentration , ...
 len_concen_radius  )



switch  PSF_Func
            case 1 % 3D Gaussian
                  Constant =exp(-2*((xx(AAA(1,:),:).^2)+...
                                    (xx(AAA(2,:),:).^2)+...
                                    (xx(AAA(3,:),:).^2)));
                               
                  for l=1:len_concen_radius
          
                      concentration(upper_bound_save,1:Trace_size,l) =...
                          ...
                       b*(sqrt( ((xx(AAA(1,:),:).^2)+...
                                 (xx(AAA(2,:),:).^2)+...
                                 (xx(AAA(3,:),:).^2)))<=concen_radious(l));
                  end 
                  
            case 2 % 2D Gaussian-Lorentzian
                  Constant = exp(-2*((xx(AAA(1,:),:).^2)+(xx(AAA(2,:),:).^2))./...
                                                      (1+(xx(AAA(3,:),:).^2)))./...
                                                      (1+(xx(AAA(3,:),:).^2));
                                                             
                  for l=1:len_concen_radius
                      concentration(upper_bound_save,1:Trace_size,l) =...
                          ...
                      b*(sqrt( 0.5.*log(1+(xx(AAA(3,:),:).^2))+...
                                         ((xx(AAA(1,:),:).^2)+...
                                          (xx(AAA(2,:),:).^2))./...
                                       (1+(xx(AAA(3,:),:).^2)))<=concen_radious(l));
                  end
                  
       otherwise   % 2D Gaussian-Cylindrical
                  Constant =exp(-2*((xx(AAA(1,:),:).^2)+...
                                    (xx(AAA(2,:),:).^2)));
                  
                  for l=1:len_concen_radius
                      concentration(upper_bound_save,1:Trace_size,l) =...
                          ...
                      b*(sqrt(((xx(AAA(1,:),:).^2)+...
                               (xx(AAA(2,:),:).^2)))<=concen_radious(l));
                  end
                                     
end
   
end