%% Precalculation of PSF and gradiant of PSF for all PSFs in the form of function to be used in the main codes

function[Data] = PSF_calculation(Data)


    gg        = @(X,Y,Z) [];
    gg_grad_x = @(X,Y,Z) [];
    gg_grad_y = @(X,Y,Z) [];
    gg_grad_z = @(X,Y,Z) [];

for ii=1:length(Data.PSF_func)
    switch Data.PSF_func(ii)
           case 1        % 3D Gaussian PSF
        
                 gg=@(X,Y,Z) [gg(X,Y,Z) , exp(-2*( (((X-Data.Cxyz(1,ii))./Data.Wxyz(1,ii)).^2) + ...
                                                   (((Y-Data.Cxyz(2,ii))./Data.Wxyz(2,ii)).^2) + ...
                                                   (((Z-Data.Cxyz(3,ii))./Data.Wxyz(3,ii)).^2) )) ];
                
                 gg_grad_x = @(X,Y,Z) [gg_grad_x(X,Y,Z) , ...
                                 ( -4*((X-Data.Cxyz(1,ii))./(Data.Wxyz(1,ii).^2))).*...
                             exp(-2*( (((X-Data.Cxyz(1,ii))./Data.Wxyz(1,ii)).^2) + ...
                                      (((Y-Data.Cxyz(2,ii))./Data.Wxyz(2,ii)).^2) + ...
                                      (((Z-Data.Cxyz(3,ii))./Data.Wxyz(3,ii)).^2) ))];
                                  
                 gg_grad_y = @(X,Y,Z) [gg_grad_y(X,Y,Z) , ...
                                  (-4*((Y-Data.Cxyz(2,ii))./(Data.Wxyz(2,ii).^2))).*...
                             exp(-2*( (((X-Data.Cxyz(1,ii))./Data.Wxyz(1,ii)).^2) + ...
                                      (((Y-Data.Cxyz(2,ii))./Data.Wxyz(2,ii)).^2) + ...
                                      (((Z-Data.Cxyz(3,ii))./Data.Wxyz(3,ii)).^2) ))];
                                               
                 gg_grad_z = @(X,Y,Z) [gg_grad_z(X,Y,Z) , ...
                                  (-4*((Z-Data.Cxyz(3,ii))./(Data.Wxyz(3,ii).^2))).*...
                             exp(-2*( (((X-Data.Cxyz(1,ii))./Data.Wxyz(1,ii)).^2) + ...
                                      (((Y-Data.Cxyz(2,ii))./Data.Wxyz(2,ii)).^2) + ...
                                      (((Z-Data.Cxyz(3,ii))./Data.Wxyz(3,ii)).^2) ))];
                                  
                 gg_r = @(X,Y,Z) sqrt( (X./Data.Wxyz(1,ii)).^2 + ...
                                       (Y./Data.Wxyz(2,ii)).^2 + ...
                                       (Z./Data.Wxyz(3,ii)).^2 );

           case 2        % 2D Gaussian- Lorentzian PSF
                 gg=@(X,Y,Z) [gg(X,Y,Z) , exp(-2*( ((X-Data.Cxyz(1,ii))./Data.Wxyz(1,ii)).^2 + ...
                                                   ((Y-Data.Cxyz(2,ii))./Data.Wxyz(2,ii)).^2)...
                                               ./(1+((Z-Data.Cxyz(3,ii))./Data.Wxyz(3,ii)).^2))./...
                                                (1+((Z-Data.Cxyz(3,ii))./Data.Wxyz(3,ii)).^2) ];
                                            
                 gg_grad_x = @(X,Y,Z) [gg_grad_x(X,Y,Z) , ...
                           (-4*((X-Data.Cxyz(1,ii))./(Data.Wxyz(1,ii).^2))).*...
                             exp(-2*( ((X-Data.Cxyz(1,ii))./Data.Wxyz(1,ii)).^2 + ...
                                      ((Y-Data.Cxyz(2,ii))./Data.Wxyz(2,ii)).^2)...
                                  ./(1+((Z-Data.Cxyz(3,ii))./Data.Wxyz(3,ii)).^2))./...
                                  ((1+((Z-Data.Cxyz(3,ii))./Data.Wxyz(3,ii)).^2).^2)];
                              
                 gg_grad_y = @(X,Y,Z) [gg_grad_y(X,Y,Z) , ...
                           (-4*((Y-Data.Cxyz(2,ii))./(Data.Wxyz(2,ii).^2))).*...
                             exp(-2*( ((X-Data.Cxyz(1,ii))./Data.Wxyz(1,ii)).^2 + ...
                                      ((Y-Data.Cxyz(2,ii))./Data.Wxyz(2,ii)).^2)...
                                  ./(1+((Z-Data.Cxyz(3,ii))./Data.Wxyz(3,ii)).^2))./...
                                  ((1+((Z-Data.Cxyz(3,ii))./Data.Wxyz(3,ii)).^2).^2)];
                       
                 gg_grad_z = @(X,Y,Z) [gg_grad_z(X,Y,Z) , ...
                           ((2-4*( ((X-Data.Cxyz(1,ii))./Data.Wxyz(1,ii)).^2 + ...
                                     ((Y-Data.Cxyz(2,ii))./Data.Wxyz(2,ii)).^2))./...
                                     ((Data.Wxyz(3,ii)./(Z-Data.Cxyz(3,ii))).^2 -1 )).*...
                             exp(-2*( ((X-Data.Cxyz(1,ii))./Data.Wxyz(1,ii)).^2 + ...
                                      ((Y-Data.Cxyz(2,ii))./Data.Wxyz(2,ii)).^2)...
                                  ./(1+((Z-Data.Cxyz(3,ii))./Data.Wxyz(3,ii)).^2))./...
                                  ((1+((Z-Data.Cxyz(3,ii))./Data.Wxyz(3,ii)).^2).^2)];
                              
                 gg_r = @(X,Y,Z) sqrt( 0.5.*log(1+(Z./Data.Wxyz(3,ii)).^2) + ...
                                       ((X./Data.Wxyz(1,ii)).^2 + ...
                                        (Y./Data.Wxyz(2,ii)).^2 )./...
                                     (1+(Z./Data.Wxyz(3,ii)).^2));
                                  
        otherwise        % 2D Gaussian- Cylindrical PSF
                 gg=@(X,Y,Z) [gg(X,Y,Z) , exp(-2*( ((X-Data.Cxyz(1,ii))./Data.Wxyz(1,ii)).^2 + ...
                                                   ((Y-Data.Cxyz(2,ii))./Data.Wxyz(2,ii)).^2 )) ];
                                               
                 gg_grad_x = @(X,Y,Z) [gg_grad_x(X,Y,Z) , ...
                           ( -4*((X-Data.Cxyz(1,ii))./(Data.Wxyz(1,ii).^2))).*...
                             exp(-2*( ((X-Data.Cxyz(1,ii))./Data.Wxyz(1,ii)).^2 + ...
                                      ((Y-Data.Cxyz(2,ii))./Data.Wxyz(2,ii)).^2))];
                                  
                 gg_grad_y = @(X,Y,Z) [gg_grad_y(X,Y,Z) , ...
                           (-4*((Y-Data.Cxyz(2,ii))./(Data.Wxyz(2,ii).^2))).*...
                             exp(-2*( ((X-Data.Cxyz(1,ii))./Data.Wxyz(1,ii)).^2 + ...
                                      ((Y-Data.Cxyz(2,ii))./Data.Wxyz(2,ii)).^2))];
                                  
                 gg_grad_z = @(X,Y,Z) [gg_grad_z(X,Y,Z) , Z.*0 ];
                 
                 gg_r = @(X,Y,Z) sqrt( (X./Data.Wxyz(1,ii)).^2 + ...
                                       (Y./Data.Wxyz(2,ii)).^2 );
    end
end

Data.gg       =gg       ;
Data.gg_grad_x=gg_grad_x;
Data.gg_grad_y=gg_grad_y;
Data.gg_grad_z=gg_grad_z;
Data.gg_r     = gg_r    ;
end